#!/bin/bash
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#

# update working tree
cd /git/apps/exist
unset GIT_DIR
# save last commit
LAST_COMMIT=`git log -1 | awk 'NR==1 {print $2}'`
# this is basiclly a force pull
# so even if you force pushed this can still work
git fetch --all
git reset --hard origin/master

#build
./build.sh

#remove eXide from autodeploy
rm /git/apps/exist/autodeploy/eXide*

#restart
cd bin
export JAVA_HOME=/usr/lib/jvm/jre-1.6.0-openjdk
pm2 stop startup.sh
killall java
pm2 start -x startup.sh

#get the logs
cd /git/apps/Lockets
pm2 --silent delete lockets_pm2.json
pm2 flush
pm2 --silent start lockets_pm2.json

