#!/bin/bash

# update working tree
cd /git/apps/rest3d
unset GIT_DIR
export EXIST_HOME=/git/apps/exist
# save last commit
LAST_COMMIT=`git log -1 | awk 'NR==1 {print $2}'`
echo 'TODO: update apps, models , ...'
# this is basiclly a force pull
# so even if you force pushed this can still work
git fetch --all
git reset --hard origin/master


#copy rest3d app
cd /git/apps/rest3d/database/eXist/ant
ant -f install-rest3d.xml


