#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.


# Setup path to include cmake and other utils
source "$OPENSHIFT_REPO_DIR/.openshift/lib/add_local_bin_to_path"

