#!/bin/bash

# update working tree
cd /git/apps/glTF

unset GIT_DIR
# save last commit
LAST_COMMIT=`git log -1 | awk 'NR==1 {print $2}'`
# this is basiclly a force pull
# so even if you force pushed this can still work
git fetch --all
git reset --hard origin/master
git submodule update --init --recursive

cd converter/COLLADA2GLTF
cmake CMakeLists.txt
gmake


