#!/bin/bash

# update working tree
cd /git/apps/rest3d
unset GIT_DIR
# save last commit
LAST_COMMIT=`git log -1 | awk 'NR==1 {print $2}'`
# this is basiclly a force pull
# so even if you force pushed this can still work
git fetch --all
git reset --hard origin/master

cd server
npm install

#pm2 --silent -f stop logs
pm2 --silent -f delete all&
sleep 5
pm2 --silent -f delete all

#pm2 flush
rm -f /home/git/.pm2/logs/*
pm2 start pm2.json

echo 'start log server'
cd /git/apps/Lockets
pm2 --silent start lockets_pm2.json

